dataset:
  repo_id: innov_0730_4cam_ep0_92_clean
  root: /data/SUN_ht/datasets/innov_0730_4cam_ep0_92_clean
  use_imagenet_stats: false
policy:
  type: pi05
  repo_id: wu/pi05_innov_0730_4cam_ep0_92_clean_ga1
  pretrained_path: /data/SUN_ht/pi/pretrained_weights/pi05_base
  compile_model: false
  gradient_checkpointing: true
  dtype: bfloat16
  freeze_vision_encoder: false
  train_expert_only: false
  device: cuda
  normalization_mapping:
    ACTION: MEAN_STD
    STATE: MEAN_STD
    VISUAL: IDENTITY
  push_to_hub: false

output_dir: /tmp/pi05_runs_check/pi05_innov_0730_4cam_ep0_92_clean_ga1_{timestamp}
log_dir: /tmp/pi05_logs_check/pi05_innov_0730_4cam_ep0_92_clean_ga1_{timestamp}
job_name: pi05_innov_0730_4cam_ep0_92_clean_ga1
batch_size: 16
gradient_accumulation_steps: 1
steps: 16000
save_freq: 2000
log_freq: 20
num_workers: 4

wandb:
  enable: false
