dataset:
  repo_id: innov_0617_1554
  root: /media/wu/4750eeba-1063-264f-b8b7-b4e41ee3cc2f/innov/innov_0617_1554

policy:
  type: diffusion
  repo_id: wu/diffusion-innov-0617-1554
  push_to_hub: false
  device: cuda
  use_amp: false

  # Diffusion requires all selected camera features to have the same shape.
  input_features:
    observation.state:
      type: STATE
      shape: [14]
    observation.images.left_wrist:
      type: VISUAL
      shape: [3, 480, 640]
    observation.images.right_wrist:
      type: VISUAL
      shape: [3, 480, 640]
    observation.images.front:
      type: VISUAL
      shape: [3, 480, 640]
  output_features:
    action:
      type: ACTION
      shape: [14]

  # Use observations at t-2, t-1 and t.
  n_obs_steps: 10
  horizon: 64
  n_action_steps: 50
  drop_n_last_frames: 5

  vision_backbone: resnet34
  resize_shape: [224, 224]
  crop_ratio: 1.0
  crop_is_random: true
  pretrained_backbone_weights: ResNet34_Weights.IMAGENET1K_V1
  use_separate_rgb_encoder_per_camera: true

  noise_scheduler_type: DDPM
  num_train_timesteps: 100
  num_inference_steps: 10
  prediction_type: epsilon
  clip_sample: true
  clip_sample_range: 1.0

  normalization_mapping:
    VISUAL: MEAN_STD
    STATE: MIN_MAX
    ACTION: MIN_MAX

  compile_model: false

output_dir: /media/wu/4750eeba-1063-264f-b8b7-b4e41ee3cc2f/innov/innov_il/deffusion/runs/direct_config_run
job_name: diffusion_innov_0617_1554
batch_size: 16
steps: 30000
save_freq: 5000
log_freq: 50
num_workers: 4
eval_freq: 0

wandb:
  enable: false
